# Stop hook activity logger.
# Reads the Claude Code hook JSON from stdin, extracts the last real user
# request from the transcript, and appends "[timestamp] request" as one line
# to .claude/activity-log.md.
# NOTE: kept ASCII-only on purpose so Windows PowerShell 5.1 (which reads
# BOM-less .ps1 files as ANSI) cannot corrupt string literals. All Korean
# text in the log comes from runtime transcript data, read explicitly as UTF-8.
$ErrorActionPreference = 'SilentlyContinue'

# --- read stdin (hook JSON) ---
$raw = [Console]::In.ReadToEnd()
if (-not $raw) { exit 0 }
try { $data = $raw | ConvertFrom-Json } catch { exit 0 }

$transcript = $data.transcript_path
$cwd = $data.cwd
if (-not $cwd) { $cwd = (Get-Location).Path }
if (-not $transcript -or -not (Test-Path -LiteralPath $transcript)) { exit 0 }

# --- find the last genuine user prompt in the transcript (JSONL) ---
$lastPrompt = $null
foreach ($line in (Get-Content -LiteralPath $transcript -Encoding UTF8)) {
    if (-not $line -or -not $line.Trim()) { continue }
    try { $obj = $line | ConvertFrom-Json } catch { continue }
    if ($obj.type -ne 'user') { continue }

    $content = $obj.message.content
    $text = $null
    if ($content -is [string]) {
        $text = $content
    } elseif ($content) {
        # block array: skip tool_result responses, collect text blocks only
        $hasToolResult = $false
        $texts = @()
        foreach ($block in $content) {
            if ($block.type -eq 'tool_result') { $hasToolResult = $true }
            elseif ($block.type -eq 'text') { $texts += $block.text }
        }
        if ($hasToolResult) { continue }
        if ($texts.Count -gt 0) { $text = ($texts -join ' ') }
    }
    if (-not $text) { continue }

    # strip system-reminder / slash-command wrapper tags
    $text = [regex]::Replace($text, '(?s)<system-reminder>.*?</system-reminder>', '')
    $text = [regex]::Replace($text, '(?s)<command-[a-z]+>.*?</command-[a-z]+>', '')
    $text = [regex]::Replace($text, '(?s)<local-command-[a-z]+>.*?</local-command-[a-z]+>', '')
    $text = [regex]::Replace($text, '(?s)<[^>]+>', '')
    $text = ($text -replace '\s+', ' ').Trim()
    if ($text) { $lastPrompt = $text }
}
if (-not $lastPrompt) { exit 0 }

if ($lastPrompt.Length -gt 200) { $lastPrompt = $lastPrompt.Substring(0, 200) + '...' }

# --- append to the log file ---
$logFile = Join-Path $cwd '.claude\activity-log.md'
$stamp = Get-Date -Format 'yyyy-MM-dd HH:mm'
$entry = "- [$stamp] $lastPrompt"

if (-not (Test-Path -LiteralPath $logFile)) {
    Set-Content -LiteralPath $logFile -Value "# Activity Log (auto-generated by Stop hook)`r`n" -Encoding UTF8
} else {
    # skip if the previous entry has the same request text (repeat within a minute)
    $lastLine = Get-Content -LiteralPath $logFile -Tail 1 -Encoding UTF8
    if ($lastLine -and $lastLine.EndsWith($lastPrompt)) { exit 0 }
}
Add-Content -LiteralPath $logFile -Value $entry -Encoding UTF8
exit 0
