/**
 * 프론트엔드 에러 코드 (백엔드와 동기화)
 *
 * 백엔드의 errorCodes.ts와 동일한 코드 사용
 */

export const ErrorCodes = {
  // 인증 관련
  AUTH_INVALID_CREDENTIALS: 'ERR_AUTH_001',
  AUTH_TOKEN_EXPIRED: 'ERR_AUTH_002',
  AUTH_TOKEN_INVALID: 'ERR_AUTH_003',
  AUTH_TOKEN_MISSING: 'ERR_AUTH_004',
  AUTH_UNAUTHORIZED: 'ERR_AUTH_005',
  AUTH_FORBIDDEN: 'ERR_AUTH_006',
  AUTH_EMAIL_ALREADY_EXISTS: 'ERR_AUTH_007',
  AUTH_EMAIL_NOT_FOUND: 'ERR_AUTH_008',
  AUTH_PASSWORD_WEAK: 'ERR_AUTH_009',
  AUTH_PASSWORD_INCORRECT: 'ERR_AUTH_010',
  AUTH_SESSION_EXPIRED: 'ERR_AUTH_011',
  AUTH_REFRESH_TOKEN_INVALID: 'ERR_AUTH_012',

  // 비즈니스 로직 관련
  BIZ_NOT_FOUND: 'ERR_BIZ_001',
  BIZ_CUSTOMER_NOT_FOUND: 'ERR_BIZ_002',
  BIZ_PRODUCT_NOT_FOUND: 'ERR_BIZ_003',
  BIZ_SALES_NOT_FOUND: 'ERR_BIZ_004',
  BIZ_PURCHASE_NOT_FOUND: 'ERR_BIZ_005',
  BIZ_PAYMENT_NOT_FOUND: 'ERR_BIZ_006',
  BIZ_DUPLICATE_BUSINESS_NUMBER: 'ERR_BIZ_007',
  BIZ_INVALID_BUSINESS_NUMBER: 'ERR_BIZ_008',
  BIZ_ACCESS_DENIED: 'ERR_BIZ_009',
  BIZ_ALREADY_SIGNED: 'ERR_BIZ_010',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'ERR_RATE_001',
  RATE_LIMIT_AUTH_EXCEEDED: 'ERR_RATE_002',
  RATE_LIMIT_API_EXCEEDED: 'ERR_RATE_003',

  // 파일 업로드
  FILE_TOO_LARGE: 'ERR_FILE_001',
  FILE_INVALID_TYPE: 'ERR_FILE_002',
  FILE_INVALID_EXTENSION: 'ERR_FILE_003',
  FILE_NOT_FOUND: 'ERR_FILE_004',
  FILE_UPLOAD_FAILED: 'ERR_FILE_005',
  FILE_TOO_MANY: 'ERR_FILE_006',
  FILE_INVALID_NAME: 'ERR_FILE_007',
  FILE_MIME_MISMATCH: 'ERR_FILE_008',

  // CSRF
  CSRF_TOKEN_INVALID: 'ERR_CSRF_001',
  CSRF_TOKEN_MISSING: 'ERR_CSRF_002',
  CSRF_TOKEN_EXPIRED: 'ERR_CSRF_003',

  // 서버 오류
  SRV_INTERNAL_ERROR: 'ERR_SRV_001',
  SRV_SERVICE_UNAVAILABLE: 'ERR_SRV_002',
  SRV_TIMEOUT: 'ERR_SRV_003',
  SRV_NOT_IMPLEMENTED: 'ERR_SRV_004',

  // 유효성 검증
  VAL_INVALID_INPUT: 'ERR_VAL_001',
  VAL_MISSING_REQUIRED_FIELD: 'ERR_VAL_002',
  VAL_INVALID_EMAIL: 'ERR_VAL_003',
  VAL_INVALID_PHONE: 'ERR_VAL_004',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
